DROP TABLE PROPIEDAD;
DROP TABLE IMAGE_PROPIEDAD;
DROP TABLE INTERESADO;
DROP TABLE CLIENTE;
DROP TABLE PROP_APLICADAS;
DROP TABLE USUARIO;
DROP TABLE IMAGE_USUARIO;

---- CREACI'ON DE TABLAS DE BASE DE DATOS------------------

CREATE TABLE PROPIEDAD (
	  NUMERO_PROPIEDAD NUMERIC,
      NOMBRE TEXT,
	  AUTOR TEXT, -- (PERSONA O EMPRESA)
	  TAMANO NUMERIC,
	  M_CUADRADOS NUMERIC,
	  TIPO_PROPIEDAD TEXT, -- (VIVIENDA, APARTAMENTO, EDIFICIO COMERCIAL, BODEGA, OTRO
	  TIPO_DISPONIBILIDAD TEXT,-- (ALQUILER, VENNTA, AMBOS)
	  ESTADO_CONSTRUCCION TEXT,
	  DESCRIPCION TEXT,
	  LOCALIDAD TEXT,
	  CIUDAD  TEXT,
	  PROVINCIA TEXT,
	  CANTIDAD_HABITACIONES NUMERIC,
	  CANTIDAD_BANOS NUMERIC,
	  CANTIDAD_COCHERAS NUMERIC,
	  CANTIDAD_PISOS NUMERIC,
	  FECHA_PUBLICACION TEXT,
	  PRIMARY KEY(NUMERO_PROPIEDAD),
	  FOREIGN KEY(AUTOR) REFERENCES INTERESADO(EMAIL)
);


CREATE TABLE IMAGE_PROPIEDAD(	  
	  NOMBRE TEXT,
	  NUMERO_PROPIEDAD NUMERIC,
	  URL TEXT,
	  PRIMARY KEY(NOMBRE),
	  FOREIGN KEY(NUMERO_PROPIEDAD) REFERENCES PROPIEDAD(NUMERO_PROPIEDAD)
);

-- DROP TABLE LOCALIZACION;


-- DROP TABLE VIVIENDA_APARTAMENTO;
--CREATE TABLE VIVIENDA_APARTAMENTO(
--      CANTIDAD_HABITACIONES NUMERIC,
--	  CANTIDAD_BANOS NUMERIC,
--	  CANTIDAD_COCHERAS NUMERIC,
--	  CANTIDAD_PISOS NUMERIC,
--	  PROPIEDAD NUMERIC,
--	  PRIMARY KEY(PROPIEDAD),
--	  FOREIGN KEY(PROPIEDAD) REFERENCES PROPIEDAD(NUMERO_PROPIEDAD)
--);


CREATE TABLE INTERESADO(
		NOMBRE TEXT,
		TELEFONO TEXT,
		EMAIL TEXT,
		PROVINCIA TEXT,
		UBICACION TEXT,
		-- PASSWORD TEXT,
		PRIMARY KEY(EMAIL)
);

--INSERT INTO INTERESADO VALUES('USER2','46583256','user2@gmail.com','Alajuela','1 km al norte','USER123');


CREATE TABLE CLIENTE(
		NOMBRE TEXT,
		TELEFONO TEXT,
		EMAIL TEXT,
		PROVINCIA TEXT,
		UBICACION TEXT,
		PROPIEDAD_REQUERIDA TEXT, --(VIVIENDA, APARTAMENTO, EDIFICIO COMERCIAL, BODEGA, ETC.).
		-- PASSWORD TEXT,
		PRIMARY KEY(EMAIL)
);


--INSERT INTO CLIENTE VALUES('USER1','46583256','user1@gmail.com','Alajuela','1 km al norte','VIVIENDA','USER123');


CREATE TABLE PROP_APLICADAS(
       EMAIL_CLIENTE TEXT,
	   PROPIEDAD NUMERIC,
	   MENSAJE TEXT,
	   FECHA_APLICADA TEXT,
	   PRIMARY KEY(EMAIL_CLIENTE,PROPIEDAD),
	   FOREIGN KEY(PROPIEDAD) REFERENCES PROPIEDAD(NUMERO_PROPIEDAD),
	   FOREIGN KEY(EMAIL_CLIENTE) REFERENCES CLIENTE(EMAIL)
);


CREATE TABLE USUARIO (
			USERNAME TEXT,
			EMAIL TEXT,
			PASSWORD TEXT,
			LAST_MODIFIED TEXT,
			TIPO_USUARIO TEXT,
			PRIMARY KEY(EMAIL) 
);

--INSERT INTO USUARIO VALUES('USER1','user1@gmail.com','USER123','24/06/2018','ADMIN');


CREATE TABLE IMAGE_USUARIO(	  
	  NOMBRE TEXT,
	  EMAIL TEXT,
	  URL TEXT,
	  PRIMARY KEY(NOMBRE),
	  FOREIGN KEY(EMAIL) REFERENCES USUARIO(EMAIL)
);


--CREATE TABLE `FACTURA` ( `NUMERO` INTEGER, `FECHA` TEXT, `CLIENTE` TEXT, `IMPUESTOS` NUMERIC, `MONTOTOTAL` NUMERIC, PRIMARY KEY(`NUMERO`) )